FROM        python:3.9-slim-buster

LABEL       author="Classixz" maintainer="classixz@undeaduprising.net"

RUN         apt update \
            && apt -y install git gcc g++ ca-certificates dnsutils curl iproute2 ffmpeg procps chromium xvfb chromium-driver wget libportaudio2 libasound-dev libdbus-glib-1-2 libstdc++6 \
            && useradd -m -d /home/container container

RUN         pip install -U playwright python-dotenv PyVirtualDisplay sounddevice soundfile

RUN         playwright install --with-deps chrome

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./../entrypoint.sh /entrypoint.sh
CMD         ["/bin/bash", "/entrypoint.sh"]